#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2021 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");

exit_on_bootup();

$a_hasync = config_read_array('hasync', false);
if (empty($a_hasync['disconnectppps'])) {
    exit(0);
}

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if (!in_array($type, ['BACKUP', 'INIT', 'MASTER'])) {
   log_msg("CARP '$type' event unknown from source '{$subsystem}'");
   exit(1);
} elseif (!strstr($subsystem, '@')) {
   log_msg("CARP '$type' event triggered from wrong source '{$subsystem}'");
   exit(1);
}

list ($vhid, $iface) = explode('@', $subsystem);

$leader = interface_ppps_carp_leader();
if ($leader !== null) {
    /* all PPP links follow one VIP, other VIPs are irrelevant */
    if ($leader['vhid'] != $vhid || $leader['device'] != $iface) {
        exit(0);
    }
} else {
    /* PPP stores ports as configured interfaces or devices */
    $ports = [];
    foreach (config_read_array('ppps', 'ppp', false) as $ppp) {
        $ports = array_merge($ports, interface_ppps_hardware($ppp['if']));
    }
    if (!in_array($iface, $ports)) {
        exit(0);
    }
}

log_msg("CARP '$type' event from {$subsystem}, converging PPP links");
interfaces_ppps_carp_sync();
